fruit:
  list:
    - name: banana
      color: yellow
    - name: apple
      color: red
#@Value test-----------------------
#property:
#    test:
#        name: property depth test
#propertyTest: test
#propertyTestList: a,b,c
#-----------------------------------
#@ConfigurationProperties test------